import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const fontNumeric = Geist_Mono({subsets:['latin'],variable:'--font-numeric'});

const fontBody = Geist({subsets:['latin'],variable:'--font-body'});

const fontDisplay = Geist({subsets:['latin'],variable:'--font-display'});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        fontDisplay.variable,
        fontBody.variable,
        fontNumeric.variable
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
